image:
  repository: ghcr.io/dhanraj2525/my-service
  tag: ""                   # Jenkins writes commit hash here
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: false
  className: nginx
  host: my-service.dev.example.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  APP_ENV: development
  LOG_LEVEL: debug
