image:
  repository: ghcr.io/dhanraj2525/my-service
  tag: "16-0827906c" # Jenkins writes commit hash here
  pullPolicy: IfNotPresent
replicaCount: 2
ingress:
  enabled: false
  className: nginx
  host: my-service.staging.example.com
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
env:
  APP_ENV: staging
  LOG_LEVEL: info
