apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dhanraj2525/k8s-gitops-repo.git
    targetRevision: HEAD
    path: charts/my-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    # NO automated block here = manual sync only
    syncOptions:
      - CreateNamespace=true