apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-prod
  namespace: argocd
  labels:
    app: my-service
    env: production
spec:
  project: default
  source:
    repoURL: git@github.com:dhanraj2525/k8s-gitops-repo.git
    targetRevision: main
    path: charts/my-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml       # ← Prod overrides
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2